export const menuData = [
    {
        id: 1,
        name: "아메리카노",
        price: 4000,
        image: "/nnn99/src/assets/cafe/amriocano.jpg",
        category: "Coffee",
    },
    {
        id: 2,
        name: "라떼",
        price: 4300,
        image: "nnn99/src/assets/cafe/lette.jpg",
        category: "Coffee",
    },
    {
        id: 3,
        name: "모카 라떼",
        price: 4700,
        image: "/nnn99/src/assets/cafe/moca.jpg",
        category: "Coffee",
    },
    {
        id: 4,
        name: "돌체라떼",
        price: 5300,
        image: "/nnn99/src/assets/cafe/dollcha.jpg",
        category: "Coffee",
    },
    {
        id: 5,
        name: "말차라떼",
        price: 5600,
        image: "nnn99/src/assets/cafe/non1.jpg",
        category: "Non Coffe",
    },
    {
        id: 6,
        name: "클래식 밀크티",
        price: 6000,
        image: "/nnn99/src/assets/cafe/non2.jpg",
        category: "Non Coffe",
    },
    {
        id: 7,
        name: "얼그레이티",
        price: 4500,
        image: "nnn99/src/assets/cafe/tea1.jpg",
        category: "Non Coffe",
    },
    {
        id: 8,
        name: "히비스커스 티",
        price: 4700,
        image: "/nnn99/src/assets/cafe/tea2.jpg",
        category: "Non Coffe",
    },
    {
        id: 9,
        name: "흑임자 롤케이크",
        price: 6200,
        image: "nnn99/src/assets/cafe/cake1.jpg",
        category: "Dessert",
    },
    {
        id: 10,
        name: "초코레이어 케이크",
        price: 6500,
        image: "/nnn99/src/assets/cafe/cake2.jpg",
        category: "Dessert",
    },
    {
        id: 11,
        name: "말차 롤케이크",
        price: 6200,
        image: "nnn99/src/assets/cafe/cake3.jpg",
        category: "Dessert",
    },
    {
        id: 12,
        name: "밀크티 케이크",
        price: 6800,
        image: "/nnn99/src/assets/cafe/cake4.jpg",
        category: "Dessert",
    },
];
